### 1. Take fruits.csv and perform classification based on Decision tree. What is the success rate?

### Importing the libraries

In [28]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

### Importing the dataset

In [50]:
ds = pd.read_csv('fruits.csv')
ds=ds.drop('Index',axis=1)
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [53]:
ds

Weight  size   Class
0       69  4.39  orange
1       68  4.21  orange
2       65  4.28  orange
3       72  5.85   apple
4       67  4.74  orange
5       73  5.50   apple
6       70  5.65   apple
7       75  5.85   apple
8       74  5.90   apple
9       65  4.80  orange
10      73  5.50   apple
11      70  5.30   apple
12      74  5.50   apple
13      68  4.80  orange
14      74  5.75   apple
15      75  5.85   apple
16      64  4.90  orange
17      67  4.80  orange
18      65  4.75  orange
19      66  4.80  orange

### Splitting the dataset into the Training set and Test set

In [54]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [55]:
print(X_train)

[[67.    4.8 ]
 [70.    5.65]
 [68.    4.8 ]
 [67.    4.74]
 [65.    4.28]
 [73.    5.5 ]
 [74.    5.75]
 [65.    4.8 ]
 [75.    5.85]
 [64.    4.9 ]
 [70.    5.3 ]
 [72.    5.85]
 [69.    4.39]
 [75.    5.85]
 [74.    5.5 ]]


In [56]:
print(y_train)

['orange' 'apple' 'orange' 'orange' 'orange' 'apple' 'apple' 'orange'
 'apple' 'orange' 'apple' 'apple' 'orange' 'apple' 'apple']


In [57]:
print(X_test)

[[65.    4.75]
 [68.    4.21]
 [66.    4.8 ]
 [74.    5.9 ]
 [73.    5.5 ]]


In [58]:
print(y_test)

['orange' 'orange' 'orange' 'apple' 'apple']


### Feature Scaling

In [59]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [60]:
print(X_train)

[[-0.7778427  -0.7467675 ]
 [ 0.03617873  0.85076364]
 [-0.50650222 -0.7467675 ]
 [-0.7778427  -0.8595344 ]
 [-1.32052365 -1.72408066]
 [ 0.85020016  0.56884638]
 [ 1.12154064  1.03870848]
 [-1.32052365 -0.7467675 ]
 [ 1.39288112  1.22665332]
 [-1.59186413 -0.55882266]
 [ 0.03617873  0.1929567 ]
 [ 0.57885968  1.22665332]
 [-0.23516175 -1.51734134]
 [ 1.39288112  1.22665332]
 [ 1.12154064  0.56884638]]


In [61]:
print(X_test)

[[-1.32052365 -0.84073992]
 [-0.50650222 -1.85564205]
 [-1.04918318 -0.7467675 ]
 [ 1.12154064  1.32062574]
 [ 0.85020016  0.56884638]]


### Training the Decision Tree Classification model on the Training set

In [62]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

### Predicting a new result

In [70]:
print(classifier.predict(sc.transform([[100,2.3]])))

['orange']


### Predicting the Test set results

In [64]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['orange' 'orange']
 ['orange' 'orange']
 ['orange' 'orange']
 ['apple' 'apple']
 ['apple' 'apple']]


### Making the Confusion Matrix

In [67]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[2 0]
 [0 3]]


1.0